version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: benpharma-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # command: redis-server --appendonly yes --requirepass yourStrongPassword123
    # 💡 Set REDIS_PASSWORD in a non-versioned .env file and reference as an arg or env below.
    command: redis-server --appendonly yes
    # If you need a password, use: --requirepass ${REDIS_PASSWORD} (and set REDIS_PASSWORD in your .env)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
