version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: benpharma-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # 💡 Set REDIS_PASSWORD in a non-versioned .env file for security
    command: redis-server --appendonly yes
    # To add authentication, use environment variables:
    # command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
